name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Publish

    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      id: version
      uses: PaulHatch/semantic-version@v5.0.0-alpha2
      with:
        search_commit_body: true
        version_format: "${major}.${minor}.${patch}+${increment}"

    - name: Print Version
      run: echo "Version is ${{ steps.version.outputs.version }}"

    - name: Print Version 2
      run: echo "Version is $VERSION"
      env:
        VERSION=${{ steps.version.outputs.version }}

    - name: Check overriding
      run: |
        VERSION=latest
        echo "Overridden version is $VERSION"
      env:
        VERSION=${{ steps.version.outputs.version }}